version: '3.8'

services:
  db:
    build:
      context: ./db-mysql/
      dockerfile: Dockerfile 
    container_name: db-express
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}    

networks:
  public:
  private:
volumes:
  db-data:

