version: '3.9'

services:
  db:
    image: mysql
    container_name: db-express
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD:  ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}    
    volumes:
      - ./db-mysql/db.sh:/docker-entrypoint-initdb.d/db.sh
      - ./db-mysql/db.sql:/db.sql

networks:
  public:
  private:
volumes:
  db-data:

